#ifndef MENU_SETDATE_H_
#define MENU_SETDATE_H_

#include <stdint.h>

#define MENU_SETDATE_YEAR_MONTH_SEPARATOR_X 7
#define MENU_SETDATE_YEAR_MONTH_SEPARATOR_Y 1
#define MENU_SETDATE_MONTH_DAY_SEPARATOR_X 10
#define MENU_SETDATE_MONTH_DAY_SEPARATOR_Y 1

#define MENU_SETDATE_YEAR_X 3
#define MENU_SETDATE_YEAR_Y 1
#define MENU_SETDATE_MONTH_X 8
#define MENU_SETDATE_MONTH_Y 1
#define MENU_SETDATE_DAY_X 11
#define MENU_SETDATE_DAY_Y 1

#define MENU_SETDATE_YEAR_FORMAT_X 3
#define MENU_SETDATE_YEAR_FORMAT_Y 0
#define MENU_SETDATE_MONTH_FORMAT_X 8
#define MENU_SETDATE_MONTH_FORMAT_Y 0
#define MENU_SETDATE_DAY_FORMAT_X 11
#define MENU_SETDATE_DAY_FORMAT_Y 0

#define MENU_SETDATE_YEAR_MONTH_FORMAT_SEPARATOR_X 7
#define MENU_SETDATE_YEAR_MONTH_FORMAT_SEPARATOR_Y 0
#define MENU_SETDATE_MONTH_DAY_FORMAT_SEPARATOR_X 10
#define MENU_SETDATE_MONTH_DAY_FORMAT_SEPARATOR_Y 0

void menuSetDate(uint8_t flags);

#endif /* MENU_SETDATE_H_ */
