#ifndef MENU_DCF77LASTSYNCHRONIZATION_H_
#define MENU_DCF77LASTSYNCHRONIZATION_H_

#include <stdint.h>

#define MENU_DCF77LASTSYNCHRONIZATION_NEVER_X 5
#define MENU_DCF77LASTSYNCHRONIZATION_NEVER_Y 0

#define MENU_DCF77LASTSYNCHRONIZATION_TIME_X 4
#define MENU_DCF77LASTSYNCHRONIZATION_TIME_Y 0

#define MENU_DCF77LASTSYNCHRONIZATION_DATE_X 3
#define MENU_DCF77LASTSYNCHRONIZATION_DATE_Y 1

#define MENU_DCF77LASTSYNCHRONIZATION_DAYOFWEEK_X 10
#define MENU_DCF77LASTSYNCHRONIZATION_DAYOFWEEK_Y 0

void menuDcf77LastSynchronization(uint8_t flags);

#endif /* MENU_DCF77LASTSYNCHRONIZATION_H_ */
