#ifndef MENU_EDITMONTH_H_
#define MENU_EDITMONTH_H_

#include <stdint.h>

#define MENU_EDITMONTH_TITLE_X 1
#define MENU_EDITMONTH_TITLE_Y 0
#define MENU_EDITMONTH_TITLE_OFFSET 3

#define MENU_EDITMONTH_PROFILE_X 1
#define MENU_EDITMONTH_PROFILE_Y 1
#define MENU_EDITMONTH_PROFILE_OFFSET 3

#define MENU_EDITMONTH_DISPLAY_DAYS_COUNT 5

#define MENU_EDITMONTH_WEEK_SEPARATOR_CHAR CUSTOMCHARS_VERTICAL_THICK_LINE_ANSI

#define MENU_EDITMONTH_SAVE_X 1
#define MENU_EDITMONTH_SAVE_Y 1

#define MENU_EDITMONTH_CANCEL_X 9
#define MENU_EDITMONTH_CANCEL_Y 1

void menuEditMonth(uint8_t flags);

void menuEditMonthSet(uint8_t month);

#endif /* MENU_EDITMONTH_H_ */
