#ifndef MENU_DCF77SYNCHRONIZATION_H_
#define MENU_DCF77SYNCHRONIZATION_H_

#include <stdint.h>

#define MENU_DCF77SYNCHRONIZATION_HOUR_HIGHLIGHT_X 8
#define MENU_DCF77SYNCHRONIZATION_MINUTE_HIGHLIGHT_X 13

#define MENU_DCF77SYNCHRONIZATION_FOR_HIGHLIGHT_X 7
#define MENU_DCF77SYNCHRONIZATION_FOR_FORMAT "%4d"
#define MENU_DCF77SYNCHRONIZATION_FOR_MIN 1
#define MENU_DCF77SYNCHRONIZATION_FOR_MAX 1440

void menuDcf77Synchronization(uint8_t flags);

#endif /* MENU_DCF77SYNCHRONIZATION_H_ */
