#ifndef MENU_MAIN_H_
#define MENU_MAIN_H_

#include <stdint.h>
#include "../common.h"

#define MENU_MAIN_SPLASH_TICKS TICKS_PER_SECOND
#define MENU_MAIN_SPLASH_X 2
#define MENU_MAIN_SPLASH_Y 0

#define MENU_MAIN_SECOND_SEPARATOR_TOGGLE_TICKS (TICKS_PER_SECOND / 2)
#define MENU_MAIN_SYNCHRONIZATION_FINDING_TOGGLE_TICKS (TICKS_PER_SECOND / 2)

#define MENU_MAIN_HOUR_MINUTE_SEPARATOR_X 2
#define MENU_MAIN_HOUR_MINUTE_SEPARATOR_Y 0
#define MENU_MAIN_MINUTE_SECOND_SEPARATOR_X 5
#define MENU_MAIN_MINUTE_SECOND_SEPARATOR_Y 0

#define MENU_MAIN_HOUR_X 0
#define MENU_MAIN_HOUR_Y 0
#define MENU_MAIN_MINUTE_X 3
#define MENU_MAIN_MINUTE_Y 0
#define MENU_MAIN_SECOND_X 6
#define MENU_MAIN_SECOND_Y 0

#define MENU_MAIN_DAY_MONTH_SEPARATOR_X 2
#define MENU_MAIN_DAY_MONTH_SEPARATOR_Y 1
#define MENU_MAIN_MONTH_YEAR_SEPARATOR_X 5
#define MENU_MAIN_MONTH_YEAR_SEPARATOR_Y 1

#define MENU_MAIN_DAY_X 0
#define MENU_MAIN_DAY_Y 1
#define MENU_MAIN_MONTH_X 3
#define MENU_MAIN_MONTH_Y 1
#define MENU_MAIN_YEAR_X 6
#define MENU_MAIN_YEAR_Y 1

#define MENU_MAIN_DAYOFWEEK_X 11
#define MENU_MAIN_DAYOFWEEK_Y 1

#define MENU_MAIN_PROFILE_X 11
#define MENU_MAIN_PROFILE_Y 0

#define MENU_MAIN_NEXT_BELL_X 14
#define MENU_MAIN_NEXT_BELL_Y 0
#define MENU_MAIN_NEXT_BELL_FORMAT "%2d"
#define MENU_MAIN_NEXT_BELL_NONE_TEXT "--"

#define MENU_MAIN_SYNCHRONIZATION_ICON_X 15
#define MENU_MAIN_SYNCHRONIZATION_ICON_Y 1

#define MENU_MAIN_SYNCHRONIZATION_STATE_X 14
#define MENU_MAIN_SYNCHRONIZATION_STATE_Y 1

#define MENU_MAIN_TIME_TRANSITION_STATE_X 8
#define MENU_MAIN_TIME_TRANSITION_STATE_Y 0
#define MENU_MAIN_TIME_TRANSITION_STATE_NONE_CHAR ' '
#define MENU_MAIN_TIME_TRANSITION_STATE_CET_TO_CEST_CHAR '+'
#define MENU_MAIN_TIME_TRANSITION_STATE_CEST_TO_CET_CHAR '-'

void menuMain(uint8_t flags);

#endif /* MENU_MAIN_H_ */
